<div class="mtop25">

<h3>Manufacturing Sector</h3>

<div class="subheading"><strong><i>MANUFACTURING SECTOR</i></strong></div>

Manufacturing Industry in India has gone
through various phases of development over
the period of time. Since independence in 1947,
the Indian manufacturing sector has traveled
from the initial phase of building the industrial
foundation in 1950’s and early 1960’s, to the
license–permit Raj in the period of 1965–1980,
to a phase of liberalization of 1990’s, emerging
into the current phase of global competitiveness.
It has grown at a robust rate over the past ten
years and has been one of the best performing
manufacturing economy. In a country like
India, where employment generation is one of
the key policy issues, this makes this sector a
critical sector to achieve inclusiveness in growth.
<br>
<br>
The manufacturing sector has been moving
at a slower pace than the overall economy for
some time now. As a result, the sector’s
contribution to GDP has declined marginally
from 16.1 to 15.2% in the five years till March
2013. Growth rate in manufacturing reduced
from 9.7% in 2010-11 to 2.7% in 2011-12 and
1% in 2012-13. In FY13, only 3.3% of the
country’s growth was generated by
manufacturing as opposed to 83% contributed
by services. The sector is not at its strongest at
the moment, but are the manufacturing
companies in lockstep with rest of the economy?
Why do we need focus on manufacturing?
The Eleventh Plan has targeted growth in
manufacturing at 10 11 percent but actual
performance will be only about 7.7 percent. It
is a matter of concern that the manufacturing
sector has not shared in the dynamism of the
economy, not just in the XIth Plan, but even in
preceding Plan periods. As a result, the share
of the manufacturing sector in the country’s
GDP has remained stagnant at 15% (excluding
mining) for the last 30 years. This share is very
low, especially when compared with 34 percent
in China and 40 percent in Thailand. The slow
pace of growth of the manufacturing sector at
this stage of India’s development is not an
acceptable outcome, and we must ensure that
manufacturing becomes the driver for GDP
growth. This can be accomplished by the
manufacturing sector growing at a faster rate
than GDP. Only then will manufacturing be
able to attain a significant share of the GDP. In
order to attain a 25% share of the GDP by
2025, manufacturing would need to grow at a
rate of 2-4% higher than the GDP. This will
ensure that manufacturing becomes the engine
of growth for the economy.
<br>
<br>
In addition, manufacturing must provide a
large portion of the additional employment
opportunities required for India’s increasing
number of youth. Agriculture cannot be
expected to provide more jobs. On the contrary,
it should be releasing labour which has very
low productivity in agriculture to be absorbed
in other sectors. While the services sector has
been growing fast, it alone cannot absorb the
250 million additional income seekers that are
expected to join the workforce in the next 15
years. Currently, manufacturing in India
provides only 12% of jobs, and this share is
significantly less than that of other countries.
Unless manufacturing becomes an engine of
growth, providing at least 100 million additional
decent jobs, it will be difficult for India’s growth
to be inclusive.
<br>
<br>
India’s trade balance must also be improved,
and this necessitates a larger volume of exports
of manufactured goods In order to increase
exports as well as provide its internal market
with domestically produced manufactured
goods that compete with imports, India must
manufacture a much larger volume of products
at competitive costs and quality.
<br>
<br>
A strong focus on improving the “depth”
in Indian manufacturing is essential. “Depth”
can be defined as the capability and expertise
in all aspects of a product value chain.
Achieving a greater depth in manufacturing
entails ensuring a higher level of value addition
within the country. This requires focus on a
few key areas like the heavily import-skewed
capital goods sector, technological
advancements in nearly all manufacturing
sectors, and a focus on improved domestic
research and development.
<br>
<br>
The shape of global manufacturing supply
chains has changed dramatically with the
advent of computers and telecommunications.
Manufacturing has been ‘deconstructed’.
Therefore, the ability to engineer products
quickly and at low cost is becoming an
increasing source of competitive advantage. In
today’s open-trade world, it is essential that
Indian industry develop global competitiveness.
While scale remains an advantage in industry,
the deconstructed value chain of manufacturing
ensures that this scale and competitiveness can
be achieved through growth of networks of
manufacturing enterprises.
<br>
<br>
While industrial growth is the need of the
hour, we must also ensure that this growth
happens in a sustainable manner, especially
with regard to the environment. Industrial
growth is a leading factor in the degradation of
the environment. With the high rates of growth
targeted by the manufacturing sector, it must
be ensured that this growth happens in a
sustainable manner and with minimal cost to
the environment.

<div class="subheading"><strong><i>INITIATIVES TO BOOST
MANUFACTURING IN THE LAST FIVE
YEARS</i></strong></div>

Manufacturing has shown a fluctuating
growth trend measured in terms of the Index
of Industrial Production in the last few years
while there has been both moderation and
decline growth, (IIP), in the last few months as
shown in the previous sections.
<br>
<br>
Government has taken a number of
initiatives and confidence building measures for
improving the industrial climate and boosting
manufacturing in the country. Government had
approved the National Manufacturing Policy
(NMP) in October, 2011 with the objectives of
enhancing the share of manufacturing in GDP
to 25% by 2022 and creating additional 100
million jobs. One of the instruments in the NMP
is the creation of National Investment and
Manufacturing Zones (NIMZ) as planned
integrated industrial townships. Nine NIMZs
have been announced, eight of which are along
the Delhi Mumbai Industrial Corridor (DMIC).
Other measures for facilitation of industrial
investment include promotion of foreign direct
investment through consolidation of press notes
into a single document; development of industry
relevant skills and regular meetings with
industry associations and stakeholders to fast
track implementation of industrial projects.

<div class="subheading"><strong><i>National Manufacturing Policy</i></strong></div>

The Government of India notified the
National Manufacturing Policy on 4th
November, 2011 with the objective of enhancing
the share of manufacturing in GDP to 25%
within a decade and creating 100 million jobs.
It also seeks to empower rural youth by
imparting necessary skill sets to make them
employable. Sustainable development is integral
to the policy and technological value addition
in manufacturing has received special focus.
The policy is based on the principle of industrial
growth in partnership with States. The Central
Government will create the enabling policy
frame work, provide incentives for
infrastructure development on a Public Private
Partnership (PPP) basis through appropriate
financing instruments, and State Governments
will be encouraged to adopt the
instrumentalities provided in the policy. The
proposals in the policy are generally sector
neutral, location neural and technology neutral
except incentivisation of green technology.
<br>
<br>
One of the instruments in the NMP is the
creation of National Investment and
Manufacturing Zones (NIMZ) as planned
integrated industrial townships. Nine NIMZs
have been announced, eight of which are along
the Delhi Mumbai Industrial Corridor (DMIC).
Approval, in principle, has been secured for
setting up of the ninth NIMZ at Nagpur. Apart
from NIMZs, NMP also applies to
manufacturing industry throughout the country
including wherever industry is able to organize
itself into clusters and adopt a model of 
selfregulation as enunciated. Policy instruments for
manufacturing industry are applicable to both
NIMZ and Clusters. These include
Rationalization/simplification of business
regulations; simple/expeditious exit mechanism
for non viable units; Technology development,
including green technologies; Industrial training
and skill upgradation measures; Incentives for
MSMEs; Special Focus Sectors; Leveraging
infrastructure deficit and Government
procurement; and Trade Policy.
<br>
<br>
Major feature of NMP is the rationalization
and simplification of regulations based on the
basic tenet of self regulation of industry to the
extent possible. The Central/State Governments
will suspend operation of particular provisions
wherever such powers exist subject to an
alternative mechanism, annual audits by
concerned departments and third party
certification. Other features include delegation
of powers to a single body in case of other
provisions, combined application forms and
common registers as far as possible and
Systematization of inspections through third
party certification.
<br>
<br>
Some of the important initiatives
undertaken/ being undertaken under NMP,
include formulation of a scheme on Job Loss
Policy; simplification of forms / register /
returns under 13 central Labour Laws into 3
Forms; setting up of Technology Acquisition and
Development Fund (TADF) for acquisition of
appropriate technologies including environment
friendly technology.
<br>
<br>
For the effective implementation of the
NMP, a number of institutional structures have
been constituted. These include Manufacturing
Industry Promotion Board (MIPB), under the
Chairmanship of Commerce & Industry
Minister; High Level Committee (HLC) under
the Chairmanship of Secretary, DIPP; Board of
Approval (BOA) under the concerned Joint
Secretary. In addition Green Manufacturing
Committee (GMaC) has also been set up to
promote green technology for manufacturing
under NIMZ.

<div class="subheading"><strong><i>Delhi Mumbai industrial corridor (DMIC)</i></strong></div>

As part of the Japan India Special Economic
Partnership Initiative for developing requisite
infrastructure and facilitating investment, DMIC
Project was conceptualized to take benefit of
the high quality rail and road connectivity
offered by 1483 km long Delhi Mumbai
Dedicated Rail Freight Corridor (DFC), existing
rail passenger- cum- freight corridor and
National Highways. The vision of DMIC is to
create strong economic base on both the sides
of the Dedicated Freight Corridor with globally
competitive environment and state-of-the-art
infrastructure to activate local commerce,
enhance foreign investments and attain
sustainable development.
<br>
<br>
The Government of India accorded in
principle approval to the project outline of
DMIC Project in August, 2007. Twenty four
Investment Regions/ Industrial Areas across the
six States of Uttar Pradesh, Haryana, Madhya
Pradesh, Rajasthan, Gujarat and Maharashtra
were identified for development in DMIC. An
institutional framework with a dedicated Special
Purpose Vehicle (SPV) viz. Delhi Mumbai
Industrial Corridor Development Corporation
(DMICDC) was set up for project development,
coordination and implementation of the
numerous projects.
<br>
<br>
As the Master Plans progressed, it was felt
necessary and essential that new industrial cities
must be created on the back of world class
trunk infrastructure i.e. drainage, sewage, solid
waste, water supply, internal roads. Without
the trunk infrastructure the development of PPP
projects in Greenfield cities was not feasible and
may lead to real estate development without
trunk infrastructure and a developed backbone.
The Government of India, therefore, in
September, 2011 restructured the DMIC Project
with an Implementation Fund of Rs.17,500
crore to be utilized over a period of five years
and an additional project development Fund of
Rs.1000 crore. The land for the new industrial
cities will be the contribution of the State
Government. The Japanese Government have
also announced their financial support for
DMIC project to an extent of US $ 4.5 billion
for projects with Japanese participation in the
first phase of the project.
<br>
<br>
Looking at the magnitude and diversity, the
entire project has been planned to be
implemented in phases. Initially, the following
industrial cities have been taken up for
development as industrial cities:
<ol>
    <ul>
        <li>Ahmedabad-Dholera Investment
Region, Gujarat;</li>
        <li>Shendra-Bidkin Industrial Park city
near Aurangabad, Maharashtra;</li>
        <li>Manesar-Bawal Investment Region,
Haryana;</li>
        <li>Khushkhera-Bhiwadi-Neemrana
Investment Region, Rajasthan;</li>
        <li>Jodhpur-Pali-Marwar Industrial Area,
Rajasthan;</li>
        <li>Pithampur-Dhar-Mhow Investment
Region, Madhya Pradesh;</li>
        <li>Dadri-Noida-Ghaziabad Investment
Region, Uttar Pradesh;</li>
        <li>Dighi Port Industrial Area,
Maharashtra.</li>
        <li>In addition one more NIMZ is being
considered near Nagpur.</li>
    </ul>
</ol>

The overall perspective plan for the entire
DMIC Region has been completed. The Master
Planning of the first six industrial cities
mentioned above have been completed. The
concerned State Governments have initiated the
process of Land pooling/ procurement/
acquisition for the industrial cities as well as
for the Early Bird Projects. Project Development
of four (04) Gas Based Power Projects is
complete including the final Environmental
clearance.

<div class="subheading"><strong><i>PROMOTION OF BUSINESS
ENVIRONMENT</i></strong></div>

Promoting FDI- Significant changes have
been made in the FDI policy regime in the
recent times to ensure that India remains
increasingly attractive and investor-friendly.
Some of the main changes have been as follows:
Consolidation- For ease of reference, all
existing regulations on FDI were integrated into
one consolidated document. The consolidation
involved integration of 178 Press Notes, covering
various aspects of FDI policy since 1991, as also
other regulations governing FDI. The document
was released as Circular 1 of 2010, effective 1
April, 2010.
<br>
<br>
Rationalization and liberalization- In order
to make the FDI policy more liberal and
investor-friendly, further rationalization and
simplification has been carried out since.
Accordingly, a number of clarifications were
issued on various subjects, including interalia
the concepts of controlled conditions for FDI in
Agriculture/Animal Husbandry etc., valueaddition in case of mining and mineral
separation of Titanium bearing minerals and
introduction of a specific provision for
downstream investment through internal
accruals .
<br>
<br>
Subsequently, significant policy changes
were introduced in Circular 1 of 2011 effective
from 1.4.2011. These include: 
<ol>
    <ul>
        <li>flexibility in fixing pricing of convertible instruments
through a formula, rather than upfront fixation</li>
        <li>Inclusion of fresh items for issue of shares
against non-cash considerations, including
import of capital goods/ machinery/ equipment
and pre-operative/ pre-incorporation expenses</li>
        <li>Removal of the condition of prior approval
in case of existing joint ventures/technical
collaborations in the same field</li>
        <li>simplification and rationalization of guidelines
relating to down-stream investments</li>
        <li>development and production of seeds and
planting material, without the stipulation of
having to do so under controlled conditions .
FDI has also recently been permitted in Limited
Liability Partnerships (LLPs), subject to specified
conditions.</li>
    </ul>
</ol>





</div>