<div class="mtop25">

<h3>NAM</h3>


First Asian-African Conference is regarded
as a precursor to NAM. This conference was
held at Bandung, Indonesia, in April 1955
among high representatives of 29 states to
consider problems of common interest and
discuss ways and means of reaching fuller
cooperation.
<br>
<br>
The first conference of Heads of State or
Government of Non-Aligned Countries was
held at Belgrade in September 1961 and issued
a passionate appeal to the US and USSR to
"suspend their recent war preparations" and
"resume negotiation for a peaceful settlement"
of outstanding differences between them.
NAM had a strong link with decolonization.
Decolonization led to many effects in functioning
of modern world politics. NAM was one such
creature that emerged in wave of powerful
national freedom struggles which were very
critical of domination by any extra national
power. Another immediate effect was to widen
the agenda of the international system, especially
that of the United Nations General Assembly of
which the newly independent states were
members, to include subjects of interest to them
such as decolonization, racial equality, and
economic development. Another effect was to
alter the functioning of the international system
somewhat, away from the realpolitik of power
play toward norms of equity, international law,
universal participation and legitimization of
collective action by the UN.
<br>
<br>
NAM is Not Neutrality or Neutralization
Nonalignment was always different from
neutrality or neutralization, because nonalignment was a freely chosen position and not
imposed by others as in the case of neutralization. Nonaligned states never claimed to be
strictly equidistant from the two super powers
and tolerated cynical allegations of manipulating
Cold War rivalries for their own benefit. Nehru
often explained that nonalignment demanded
an active participation in the international arena
and not the passive withdrawal of a neutral.
Six-continent initiative launched by
Argentina, India, Greece, Mexico, Sweden and
Tanzania on behalf of NAM, calling for a
worldwide moratorium on the testing, production and development of nuclear weapons
and delivery systems.

<div class="subheading"><strong><i>NIEO</i></strong></div>

At a special session of the General Assembly
in 1974, a Programme for Action for the
establishment of a New International Economic
Order (NIEO) was adopted. Ideas of similar
nature were earlier aired at NAM summit in
Lusaka 1970.
<br>
<br>
The reforms demanded under NIEO fell
under five main heads as follows; Reforms in
the terms of trade and pricing for primary
products and commodities, and better access to
the markets of the advanced industrial countries
through preferences; Reforms in the major
international economic institutions, especially
the International Monetary Fund, to benefit
developing countries; Recognition of the growing
problem of Third World debt and measures to
alleviate it; Greater economic assistance and
technology transfers to developing countries;
Recognition of sovereign rights to direct national
economic policy and control the activities of
Multi-National Corporations.

<div class="subheading"><strong><i>NAM: a SWOT analysis</i></strong></div>

Most weaknesses of NAM stemmed from
the diversity of its members. Members were
drawn from every continent and therefore
lacking the common perspectives. NIEO was
weakened by victory of conservative leaders
with hard ideology in the West, especially
Margaret Thatcher in Britain and Ronald Reagan
in the US. It was certainly a setback to the cause
of international social justice. At the same time,
Nonalignment was again denigrated as 'immoral'
and 'anti-American'. Even NAM countries' ability
and willingness to implement the NIEO charter
within their own countries was correspondingly
weak.
<br>
<br>
Lack of means was a ready explanation for
the paucity of South-South cooperation. But
even when financial means were available, as
from petro-dollars generated by successive oilprice hikes, they were directed more toward
arms purchases and investments in the West.
The weaknesses of NAM stemmed from
the administrative, diplomatic, economic,
financial, institutional, and political weakness
of the individual members themselves. These
were most evident in cases of civil conflict that
racked most of Africa, and of conflict among
member states, such as between Iran and Iraq
for years of bitter war during 1980-1988, and
perennial disputes between Pakistan and India,
that NAM could neither prevent nor seriously
attempt to mediate. NAM still lacks the
mechanisms and power to resolve conflicts.
<br>
<br>
The strengths of NAM arose from the
courageous efforts of its founding leaders to
approach questions of international peace and
security from the point of view of the larger
good of humanity, to provide representatives of
distanced and newly independent states
opportunities for free discussion of issues and
interaction with each other.

<div class="subheading"><strong><i>INDIA AND THE COLD WAR</i></strong></div>

As a leader of NAM, India's response to
the ongoing Cold War was two-fold: At one
level, it took particular care in staying away
from the two alliances. Second, it raised its voice
against the newly decolonised countries
becoming part of these alliances. India's policy
was neither negative nor passive. As Nehru
reminded the world, nonalignment was not a
policy of 'fleeing away'. On the contrary, India
was in favour of actively intervening in world
affairs to soften Cold War rivalries. India tried
to reduce the differences between the alliances
and thereby prevent differences from escalating
into a full-scale war. Indian diplomats and
leaders were often used to communicate and
mediate between Cold War rivals such as in the
Korea War in the early 1950s.
<br>
<br>
It is important to remember that India
chose to involve other members of the nonaligned group in this mission. During the Cold
War, India repeatedly tried to activate those
regional and international organisations, which
were not a part of the alliances led by the US
and USSR. Nehru reposed great faith in 'a
genuine commonwealth of free and cooperating
nations' that would play a positive role in
softening, if not ending, the Cold War.
Non-alignment was not, as some suggest,
a noble international cause which had little to
do with India's real interests. A non-aligned
posture also served India's interests very directly,
in at least two ways:
<ol>
    <ul>
        <li>First, non-alignment allowed India to take
international decisions and stances that served
its interests rather than the interests of the
superpowers and their allies.</li>
        <li>Second, India was often able to balance
one superpower against the other. If India felt
ignored or unduly pressurized by one
superpower, it could tilt towards the other.
Neither alliance system could take India for
granted or bully it.</li>
    </ul>
</ol>

India's policy of non-alignment was criticised
on a number of counts. Here we may refer to
only two criticisms:
<ol>
    <ul>
        <li>First, India's non-alignment was said to be
'unprincipled'. In the name of pursuing its
national interest, India, it was said, often refused
to take a firm stand on crucial international
issues.</li>
        <li>Second, it is suggested that India was
inconsistent and took contradictory postures.</li>
    </ul>
</ol>

Having criticised others for joining alliances,
India signed the Treaty of Friendship in August
1971 with the USSR for 20 years. This was
regarded, particularly by outside observers, as
virtually joining the Soviet alliance system. The
Indian government's view was that India needed
diplomatic and possibly military support during
the Bangladesh crisis and that in any case the
treaty did not stop India from having good
relations with other countries including the US.
Non-alignment as a strategy evolved in the
Cold War context. With the disintegration of
the USSR and the end of the Cold War in 1991,
non-alignment, both as an international
movement and as the core of India's foreign
policy, lost some of its earlier relevance and
effectiveness. However, nonalignment contained
some core values and enduring ideas. It was
based on a recognition that decolonised states
share a historical affiliation and can become a
powerful force if they come together. It meant
that the poor and often very small countries of
the world need not become followers of any of
the big powers, that they could pursue an
independent foreign policy. It was also based on
a resolve to democratise the international system
by thinking about an alternative world order to
redress existing inequities. These core ideas
remain relevant even after the Cold War has
ended.



</div>