<div class="mtop25">

<h3>Volcanoes And earthquakes</h3>


<div class="subheading"><strong><i>Volcano</i></strong></div>

A volcano is a vent or opening usually
circular in form through which heated materials
consisting of gases, water, liquid lava and
fragments of rocks are ejected from the highly
heated interior to the surface of the earth.
Magma is molten rock within the Earth’s crust.
When magma erupts through the earth’s
surface it is called lava. Lava can be thick and
slow-moving or thin and fast-moving. Rock also
comes from volcanoes in other forms, including
ash (finely powdered rock that looks like dark
smoke coming from the volcano), cinders (bits
of fragmented lava), and pumice (light-weight
rock that is full of air bubbles and is formed in
explosive volcanic eruptions - this type of rock
can float on water).
<br>
<br>
Volcanic eruptions are closely associated with
several interconnected processes such as
<ol>
    <ul>
        <li>The gradual increase in temperature with
increasing depth at a rate of 1°c per 32m
due to heat generated by degeneration of
radioactive elements inside the earth.</li>
        <li>origin of magma because of lowering of
melting point caused by reduction in
pressure of overlying rocks due to fractures
caused by splitting of plates</li>
        <li>origin of gases and water vapour due to
heating of water</li>
        <li>ascent of magma due to pressure from
gases and vapour</li>
        <li>Occurrence of volcanic eruption. These
eruptions are closely associated with plate
boundaries.</li>
    </ul>
</ol>

<b>Volcanoes are classified under different
schemes:</b>
<ol>
    <ul>
        <li>Classification on the basis of periodicity
of eruptions:
<ol>
    <ul>
        <li>Active volcano e.g. Etna, Stromboli,
Pinatubo etc.</li>
        <li>Dormant volcano e.g. Vesuvius, Barren
island volcano (Andaman)</li>
        <li>Extinct volcano e.g. where no indication of future eruption is estimated.</li>
    </ul>
</ol>
</li>
        <li>
        <div class="subheading"><strong><i>Classification on the basis of the mode
of eruption:</i></strong></div>    
        <ol>
            <ul>
                <li>Volcanic of central Eruption type- Eruption
occurs through a central pipe and small
opening are rapid and violent. Such
volcanoes are very destructive and
disastrous. It is divided into 5 sub types as
follow:-
<ol>
    <ul>
        <li>Hawaiian Types: Such Volcanoes erupt
quietly due to less viscous Laves and
non-violent natures of gases. They emit
long glossy threads of red molten Lava
known as peel’s hair e.g. Hawaiian Island.</li>
        <li>Strombolian Type: The eruptions are
almost rhythmic or nearly continuous in
nature but sometimes they are interrupted by long intervals. Ex- Stromboli
volcano of Lipari island.</li>
        <li>Vulcanian Type: Such volcanoes erupt
with great force and intensity The Lava
is so viscous and pasty that these are
quickly solidified e.g. Mt. Vulcano of
Lipari Island of Mediterranean Sea.</li>
        <li>Peleean Type: Most violent and most
explosive type of volcanoes, named as
Nuee Ardente, meaning thus by glowing cloud e.g. Pelee volcano of
Martinique Island in the Caribbean Sea,
Krakatau volcano between Java and
Sumatra in Sunda strait.</li>
        <li>Visuvian type: Extremely violent and
enormous volume of gases and ashes
forms which clouds like cauliflower. This
is also called Plinian type.</li>
    </ul>
</ol>
</li>
                <li>Fissure eruption or quiet eruption type
e.g. Lava flow or flood, mud flow and
fumaroles. Large quantities of lava quietly
well up from fissure and spread out over
the surrounding countryside. Successive
lava flows results in the growth of a lava
platform which may be extensive to be
called a plateau like “Deccan” “Columbia
snake plateau”, Drakensberg mountains”,
“Victoria and Kimberley” districts of
Australia, “ Java island”.</li>
            </ul>
        </ol>
</li>
    </ul>
</ol>

<div class="subheading"><strong><i>Plate tectonics and Volcanoes</i></strong></div>
<ol>
    <ul>
        <li>
        <div class="subheading"><strong><i>Divergent plate boundaries</i></strong></div>    
        
At the mid-oceanic ridges, two tectonic
plates diverge from one another. New oceanic
crust is being formed by hot molten rock slowly
cooling and solidifying. The crust is very thin at
mid-oceanic ridges due to the pull of the tectonic
plates. The release of pressure leads to partial
melting of the mantle causing volcanism and
creating new oceanic crust. Most divergent plate
boundaries are at the bottom of the oceans,
therefore most volcanic activity is submarine,
forming new seafloor. Black smokers or deep
sea vents are an example of this kind of volcanic
activity. Where the mid-oceanic ridge is above
sea-level, volcanic islands are formed, for
example, Iceland.</li>
        <li>
        <div class="subheading"><strong><i>Convergent plate boundaries</i></strong></div>    
        
Subduction zones are places where two
plates, usually an oceanic plate and a continental
plate, collide. In this case, the oceanic plate
subducts or submerges under the continental
plate forming a deep ocean trench just offshore.
Water released from the subducting plate lowers
the melting temperature of the overlying mantle
wedge, creating magma. This magma tends to
be very viscous due to its high silica content so
that it often does not reach the surface and cools
at depth. When it does reach the surface, a
volcano is formed. Typical examples for this kind
of volcano are Mount Etna and the volcanoes
in the Pacific Ring of Fire.</li>
        <li>
        <div class="subheading"><strong><i>Hotspots</i></strong></div>    
        
Hotspots are not usually located on the
edges of tectonic plates, above mantle plumes,
where the convection of the Earth’s mantle
creates a column of hot material that rises until
it reaches the crust, which tends to be thinner
than in other areas of the Earth. The
temperature of the plume causes the crust to melt
and form pipes, which can vent magma. Because
the tectonic plates move whereas the mantle
plume remains in the same place, each volcano
becomes dormant after a while and a new
volcano is then formed as the plate shifts over
the hotspot. The Hawaiian Islands are thought
to be formed in such a manner, as well as the
Snake River Plain, with the Yellowstone Caldera
of the North American plate currently above the
hot spot. Another example is India’s Deccan
plateau which is the result of lava outflow from
the Reunion hotspot.</li>
    </ul>
</ol>

<div class="subheading"><strong><i>Topography produced by volcanoes:</i></strong></div>
<ol>
    <ul>
        <li>Cinder or ash cone: They are of low height
and are formed of volcanic dust, ashes and
pyroclastic matter. Its formation takes place
due to accumulation of finer particles
around the volcanoes vent.</li>
        <li>Shield volcanoes: So named for their
broad, shield-like profiles, are formed by
the eruption of low-viscosity lava that can
flow a great distance from a vent, but not
generally explode catastrophically. Since
low-viscosity magma is typically low in
silica, shield volcanoes are more common
in oceanic settings. The Hawaiian volcanic
chain is a series of shield cones, and they
are common in Iceland as well.</li>
        <li>Composite cones: They are formed due to
the accumulation of different layers of
various volcanic materials.</li>
        <li>Parasite cones: When lava comes out of
the minor pipes coming out of the main
central pipe, parasite cones are formed.</li>
        <li>Basic lava cone: It has less quantity of silica
in its lava.</li>
        <li>Acidic lava cone: It has more silica in its
lava.</li>
        <li>Lava domes: These are formed due to
accumulation of solidified lavas around the
volcanic vents.</li>
        <li>Lava plugs: They are formed due to
plugging of volcanic pipes and vents when
volcano becomes extinct.</li>
        <li>Craters: The depression formed at the
mouth of a volcanic vent is called a crater.
When it is filled with water, it becomes a
‘crater lake’ e.g. Lake Lonar in
Maharashtra.</li>
        <li>Calderas: Generally enlarged form of
craters is called caldera. It is formed due to
subsidence of a crater.</li>
        <li>Geysers: They are intermittent hot springs
that from time to time spout steam and hot
water from their craters.</li>
        <li>Fumaroles: It is a vent through which
there is emission of gases and water vapour.</li>
        <li>Cryptodomes: These are formed when
viscous lava forces its way up and causes
a bulge. The 1980 eruption of Mount St.
Helens was an example. Lava under great
pressure forced a bulge in the mountain,
which was unstable and slid down the
north side.</li>
        <li>A supervolcano is a large volcano that
usually has a large caldera and can
potentially produce devastation on an
enormous, sometimes continental, scale.
Such eruptions can cause severe cooling of
global temperatures for many years
afterwards because of the huge volumes
of sulphur and ash erupted. They are the
most dangerous type of volcano. Examples
include Yellowstone Caldera in
Yellowstone National Park and Valles
Caldera in New Mexico (both western
United States), Lake Taupo in New
Zealand, Lake Toba in Sumatra and
Ngorogoro Crater in Tanzania.
<br>
<br>
Supervolcanoes are hard to identify
centuries later, given the enormous areas
they cover. Large igneous provinces are
also considered supervolcanoes because of
the vast amount of basalt lava erupted,
but are non-explosive.</li>
    </ul>
</ol>

<div class="subheading"><strong><i>Distribution of volcanoes</i></strong></div>

Volcanoes are unevenly distributed over the
earth and vast areas have no active volcanoes at
all. There are no volcanoes in Australia. In Asia,
they are largely concentrated in circum-pacific
region and Africa has a few of them. Thus, the
pacific belt is truly known as the “ring of fire”
because of the largest number of active volcanoes
along the coasts of America and Asia around
this region. Iceland, Sicily and Japan are the
biggest volcanic islands in the world. Most of the
volcanoes in the world occur along linear belts
or lines of weakness marked by intense folding
and faulting.

<div class="subheading"><strong><i>Earthquake</i></strong></div>

An earthquake is a vibration or oscillation
of the surface of the earth caused by a transient
disturbance of the elastic or gravitational
equilibrium of the rocks at or beneath the surface.
The magnitude or intensity of energy released
by an earthquake is measured by the richter scale.
The place of the origin of an earthquake is called
focus which is hidden inside the earth. The place
on the ground surface which is perpendicular
to the buried focus is called ‘epicentre’. Seismic
waves are recorded by an instrument called
‘seismograph’. Isoseismal lines join places which
experience the earthquake at the same time.

<div class="subheading"><strong><i>Causes of Earthquakes:</i></strong></div>

If seen broadly we can say that earthquakes
are caused due to two major reasons. The first
reason is the eruption of volcanoes, which are
sudden. Volcanoes are seats of inner disturbance
and can affect the plates which are the second
cause of earthquakes. Earthquakes are caused
due to disturbance in the movement of plates,
which again can be caused due to various
reasons like under-crust waves or cracks in the
plates.
<ol>
    <ul>
        <li>
        <div class="subheading"><strong><i>Plate Tectonic Theory</i></strong></div>    
        
The outer layer of the earth is divided into
many sections known as plates, which are
floating on the molten magma beneath the
earth’s crust. Now the movement of these plates
is determined by the convection current in the
molten magma. Therefore after intervals there
are plates that get submerged in the molten
magma and there are plates that rise upwards
and at times even new crust is formed from the
molten magma which in turn forms a new plate
until it connects itself with the already existing
ones. At times these plates and can be pushed
up to form mountains and hills and the
movement is so slow that it is really hard to
comprehend that there is any movement at all.
The movement and the results come out to be
visible suddenly. Now these plates are the bases
on which the continents stand and when these
plates move the continents also move. Most of
the earthquakes occur on the edges of the plates
where a plate is under, on or across another
plate. This movement disrupts the balance and
position of all plates, which leads to tremors,
which are called earthquakes.</li>
        <li>
        <div class="subheading"><strong><i>Volcanic Eruptions</i></strong></div>    
        
When volcanoes erupt it is because the
molten magma under the crust of the earth is
under enormous pressure and to release that
pressure it looks for an opening and exerts
pressure on the earth’s crust and the plate in turn.
A place, which is the seat of an active volcano,
is often prone to earthquakes as well.
Earthquakes are also caused after a volcanic
eruption since the eruption also leads to a
disturbance in the position of plates, which either
move further or resettle and can result into severe
or light tremors.
<br>
<br>
The excessive exploitation of earth’s
resources for our own benefits like building dams
to store large volumes of water (earthquake at
Koyna Nagar Township) and blasting rocks and
mountains to build bridges and roads is also the
reason behind such natural disruptions.
Effects
<ol>
    <ul>
        <li>Landslides and damming of the rivers in
highland regions.</li>
        <li>Causes depression forming lakes. May
cause faults, thrusts, folds, etc</li>
        <li>Formation of cracks or fissures in the
epicenter region and some- times water,
mud, gas are ejected from it.</li>
        <li>Causes the raising or lowering of parts of
the sea floor e.g. “Sangami bay” in 1923.
This causes “tsunamis” or tidal waves.</li>
        <li>May change surface drainage &
underground circulation of water like the
sudden disappearance of springs in some
places.</li>
        <li>Rising and lowering of crustal regions for
example in Alaska in 1899-16 m upliftment.</li>
        <li>Devastation of cities, fires, diseases, etc.
Classification of earthquakes</li>
    </ul>
</ol>
</li>
    </ul>
</ol>

<div class="subheading"><strong><i>Earthquakes are classified on the basis of
causative factors:</i></strong></div>
<ol>
    <ul>
        <li>Natural earthquakes: They are caused by
endogenetic forces:
    <ol>
        <ul>
            <li>Volcanic earthquake: they are caused
due to volcanic eruptions. E.g. Earthquakes caused by explosion of Krakatau
volcano in 1883 and Etna volcano in
1968.</li>
            <li>Tectonic earthquake: they are caused
due to dislocation of rock blocks during
faulting e.g. 1906 earthquake of California and 1923 earthquake of Sangami
bay, Japan etc.</li>
            <li>Isostatic earthquake: they are triggered
due to sudden disturbance in the isostatic balance at regional scale due to
imbalance in geological processes e.g.
near active mountain building zones.</li>
            <li>Plutonic earthquakes: these are deep
focus earthquakes generally located between 240 and 670 km deep.</li>
        </ul>
    </ol>
</li>
        <li>Artificial earthquakes: They are caused
due to man-made activities like pumping
water and mineral oil underground,
blasting of rocks, nuclear explosion, storage
of huge volume of water in reservoirs etc.
Examples of earthquake due to construction
of huge dams include Koyna earthquake
of 1967 and Hoover dam earthquake of
1936.</li>
    </ul>
</ol>


<div class="subheading"><strong><i>Distribution of Earthquakes</i></strong></div>

About 68% of all the earthquakes are
observed in the vast region of the pacific ocean
known as the “ring of fire” and is closely linked
with the region of crustal dislocations and
volcanic eruptions. Chile, California, Alaska,
Japan, Philippines, New Zealand constitute the
ring of fire.
<br>
<br>
Around 21% of the earthquakes occur in the
mid-word mountain belt extending parallel to
the equator from Mexico across Atlantic Ocean,
the Mediterranean Sea from Alpine-Caucasus
ranges to the Caspian, Himalayan Mountains
and the adjoining belts: the earthquakes in India
are at present mainly confined to the Himalayan
regions and its foot hills. They are also felt in the
Ganga valley.

<div class="subheading"><strong><i>Points to Remember</i></strong></div>

<ol>
    <ul>
        <li>The largest crater known to have formed
by a meteorite is Coon Butte or Barringer
crater in USA. Lonar lake of Maharashtra
is the largest meteoric Crater Lake in India.</li>
        <li>Earth’s rotational velocity at equator is 1690
km/hr.</li>
        <li>Elastic rebound theory explains
anthropogenic earthquake.</li>
        <li>Earth’s magnetic north and South Pole are
located on Prince of Wales Island in
Canada and South Victoria island in
Antarctica, respectively.</li>
        <li>“Homoseismal line” is the line joining places
that experience earthquake at the same
time.</li>
        <li>The only active volcano in India is Barren
Island in Andaman-Nicobar islands.</li>
        <li>Seismic waves that cause maximum
destruction is ‘L’ or long waves.</li>
        <li>Magnitude of earthquake is measured on
Richter scale.</li>
    </ul>
</ol>




</div>