<div class="mtop25">

<h3>Indian Nationalism</h3>



The latter half of the 19th century witnessed the
rise and growth of Indian Nationalism and from then
onwards an organised national movement started in
India. The year 1885 marks the beginning of a new
epoch in Indian history. In that year All Indian Political
Organisation was set on foot under the name of the
Indian National Congress. The Indian mind became
increasingly conscious of its political position. Indian
masses, under the National congress fought one of the
longest non-violent (to some extent violent also)
struggle to get their freedom on 15th August 1947. A
retrospective examination of the National movement
suggests three broad stages in its development.
In the first stage of its existence (1885-1905), the
vision of the Indian National Congress was dim, vague
and confused. The movement was confined to a handful
of the educated middle class intelligentsia who drew
inspiration from western liberal and radical thought.
During the second stage (1905-1919), the Congress
comes of age and its aim and scope were considerably
extended. It aimed at an all round uplift of the peoplesocial, cultural, economic and political. Swaraj or selfgovernment was the goal on the political front. Some
progressive elements within the Congress adopted
western revolutionary methods to liquidate western
imperialism.
<br>
<br>
The final stage (1919-47) was the Gandhian stage
of freedom movement. It was dominated by the objective
of Purna Swaraj or complete independence to be
achieved under the leadership of Mahatma Gandhi by
the characteristically Indian method of non-violent
non- cooperation.
<br>
<br>
There were several factors that led to the
growth of Indian nationalism.

<ol>
    <ul>
        <li><b>Impact of Foreign Rule:</b> Traditional Indian
historiography explains rise and growth of Indian
Nationalism in terms of Western response to
stimulus generated by British Raj through creation
of new institution, new opportunities, resources
etc. In other words, Indian Nationalism grew partly
as a result of colonial policies and partly as a
reaction to colonial policies.
The root of the Indian Nationalism lies in the clash
between the Indian interests and the British
colonial interest. The English in order to guard
their interest controlled tightly their Indian colony.
British colonial rulers followed modern methodspolitical, military, and economic and intellectualto establish and continue their strong hold over
India and for further economic exploitation of
India's resources. A dose of modernization was an
essential concomitant of the colonial scheme of
administration and this modernization-distorted
though it was-generated some development and
one of these was growth of Indian Nationalism.
The Indian masses felt that the industrialists of
Lancashire and the groups in Britain were
sacrificing their needs and interest to guard their
own. The economic backwardness, caused by the
exploitation of the British was the major reason for
underdevelopment of India economically, socially,
politically, culturally and intellectually. Now the
Indians greatly understood this premise.
<br>
<br>
Almost every group and community in Indian
society saw that their interests are unsafe under
British rule. Farmers were weary of the colonial
authorities. Government took a large portion of
their producer under the pretext of land revenue.
Government, police and administration all sided
with the landlords and landholders. They were
supportive of those merchant groups who deceit
the farmers and exploited them and controlled their
land. Cultivator's voice against this exploitation
was muted in the name of maintenance of law and
order. Wearers and handicraft manufactures felt
the government's authority more negatively. They
were ruined by Government policies of one way
free trade and its support to British and other
European manufacturers.
<br>
<br>
Later with early 20th century when there was a
rise in Indian capitalism and industries, the
working class found the Government siding with
the capitalist especially foreign capitalists despite
verbal assurance of upliftment of labour class
status. When ever, the working class agitated under
trade unions for their causes, the Government used
all its power to suppress the movement. Moreover,
the working class was now becoming aware of the
fact that the increasing problem of unemployment
could only be solved by an independent Indian
Government and so they participated in the freedom
struggle.
The educated middle class was also aware of the
economic and political backwardness of the country
and was using various modern means to
understand the problems of British rule. Those who
supported the British in the revolt of 1857 with the
hope of creation of a developed and modern state
of India despite foreign rule were now disheartened
and dissatisfied by seeing the evil effects of foreign
rule. They thought that the British capitalism would
develop India as it was doing so for England but
they found that the Government policies in India
were guided by the British capitalist class and were
surely devastating for India. The economic policies
of government in all fields-agriculture, heavy
industries, finance, tariffs, foreign capital
investments, foreign trade, banking etc-were all
geared to the preservation of the colonial economy.
Inspite of the British intention to the contrary,
modern capitalist enterprise made a beginning in
India in the 1860's.
<br>
<br>
This development alarmed the British textile
manufacturers who started clamoring for revision
of Indian tariff rates to suit their sectional interest.
The Pound-Rupee exchange ratios were also
manipulated to the disadvantage of Indian
industry and foreign trade. The entire development
made it clear that whenever British economic
interests clashed with Indian economic
development, the latter had to be sacrificed. The
Indian capitalist class thus thought that the
independent development and growth of
imperialism has some inner contradiction and felt
the importance of a national Government which
will support the growth and development of Indian
industrial class.
Politically, the claim of British of introduction of
self-governance in India and civilizing the people
for self-government was also deceitful. Many
English officials and politicians had openly
declared the intention of British to remain in India.
Further, the British government used its force to
suppress and prohibit the freedom of speech, press
and personal liberty instead of given them freedom,
which were basic criteria for introduction of self
governance. English writers and scholars had
already declared the inability of Indians to govern
themselves. Britain took upon itself the providential
mandate of civilizing the uncivilized population
of the world. The 'white men's Burden' carried by
English-men was a recurrent theme in the writing
of British poets, scholars administrators. Culturally,
the British's were adopting negative and antiIndian policies. They were quite negative in their
approaches when it came to Indian education,
literature, and modern ideas.
<br>
<br>
The only groups whose interest coincided with that
of the British were, the Indian land holders, the
zamindars and the princes, and therefore these
groups were supportive of British rule till its final
extinction. However, there were many among these
groups also who participated in freedom struggle
against British rule. The nationalist environment
affected many and kindled the fire of nationalism
in them. Moreover, the racial discrimination and
the policy of racial supremacy resulted in the rise
of hatred in the hearts of every self respected Indian,
of whatever group he belonged, against the British
rule. The very foreign nature of British rule also led
to the rise of nationalism among the Indians.
In short, it was the nature and characteristic of
foreign imperialism and its ill effects on the Indian
masses that resulted in the rise and growth of a
powerful anti- imperialistic movement in India.
The movement was a nationalist movement as it
was a united struggle for freedom against common
enemy, British colonial rulers.</li>
        <li><b>Establishment of Peace and Administrative
Unification of India:</b> The British sword imposed
political unity in India. Common subjection,
common institutions, common laws began to shape
India in a common mould. Despite imperial efforts
to sow communal, regional and linguistic
dissension, Pan-Indianism grew. The
establishment of political unity fostered the spirit
of one-mindedness. After the chaotic conditions of
18th century, the British rulers established peace
and orderly government in India. British scholars
take pride in the fact that Pax- Britannica brought
prolonged peace and order for the first time in
India. The British also established a highly
centralized administrative system in India. Percival
Griffiths refers to the impersonality of British
administration to be its most important
characteristics i.e., the fundamental characters of
administration did not change with the changes
of top-administrators like Secretaries of State and
Viceroys.
<br>
<br>
Further, administrative unification had important
effects in many other fields. A highly trained
professional, Indian civil service managed the
district administration in all parts of India. A
unified, judicial set up, codified civil and criminal
law rigorously enforces throughout the length and
breadth of the country imparted a new dimension
of political unity to the hitherto cultural unity that
had existed in India for centuries. In the words of
Edwyn Bevan, the British Raj was like a steelframe which held the injured body of India together
till the gradual process of internal growth had
joined the dislocated bones, knit up the torn fibers,
and enabled the patient to regain inner coherence
and unity.</li>
        <li><b>Introduction of Modern Education:</b> The
introduction of modern system of education
afforded opportunities for assimilation of modern
western ideas, which in turn gave a new direction
to Indian political thinking. The English system of
education though conceived by the rulers in the
interest of efficient administration opened to the
easily educated Indian the floodgates of liberal
European thought. The liberal and radical thought
of European writers like Milton, Shelley, Benthem,
Mill, Spencer, Rousseau and Voltaire inspired the
Indian intelligentsia with the ideals of liberty,
nationality and self government while Mazzini,
Garibaldi and Irish leaders became their political
inspirations and made clear to them the
anachronism of British rule in India.
<br>
<br>
The newly-education class usually adopted the
profession of junior administrators, lawyers,
doctors, teachers etc. Some of them visited England
to receive higher education. While in England they
saw with their own eyes the working of political
institutions in a free country. On their return to
India, these persons found the atmosphere cringing
and slavish with the total denial of basic rights to
citizens. These 'Vilayat-returned' Indians with the
ever-expanding English educated class formed the
middle class intelligentsia. This English-educated
intelligentsia, somewhat conscious of political right,
found that despite the promises contained in the
Charter Act of 1833 and the Queen's proclamation
of 1858 the doors of higher services closed to the
Indians. Thus realization from discontent and
frustration among them and the discontent proved
infections.
<br>
<br>
The spread of and popularity of the English
language in all parts of India gave to the educated
Indians a common language a lingua francathrough the medium of which they could
communicate with one another and transact their
conferences and Congress. In the absence of such a
lingua franca it would have been very difficult for
the Indians to come on a common platform or
organise a movement of all-India character.
However, we should note that the Introduction of
Modern English language did not result in the rise
of Indian Nationalism. It was the result of the
clash of interest between the English and the
Indians. The English education only made the
Indians aware of modern political ideas and
systems and also made them capable of giving
shape to the Indian National movement on
democratic and modern lines. The reality was that
the officials and staffs in the English schools
usually tried to encourage pro-British attitude
among the students. The nationalist ideas were
not the result of English education.
There was a rise of nationalism and spread of
modern ideas in China, Indonesia and other
countries of Asia and Africa despite the fact that
the number of modern Western type schools and
colleges was limited. Initially the English language
acted as lingua franca among the Indians but later
its impact was seen in wider perspective educated
groups. The English language separated the
Indians into two different groups i.e., one English
educated and the other vernacular educated
groups. Most of the political leaders,
understanding this fact tried to undo the impact of
English education. Dadabhai Naoroji, Sayed
Ahmed Khan, Ranade, Tilak, and Mahatma
Gandhi, all emphasized on imparting education
through vernaculars. In fact, as far as the rise &
growth of nationalism among the masses is
concerned, it was the result of spread of western
ideas by vernacular literatures, press and
propaganda.</li>
        <li><b>Emergence of a Modern Press:</b> The emergence of
the modern press- both English and vernacular
was another offshoot of British rule in India. It
was the Europeans who set up printing presses in
India and published newspapers and other cheap
Literature. Gradually, the vernacular press came
into existence and developed on the Western
pattern. In spite of the numerous restrictions
imposed on the press by the colonial rulers from
time to time Indian journalism made rapid strides.
The latter half of the 19th century saw an
unprecedented growth of Indian-owned English
and vernacular newspapers.
<br>
<br>
In 1857 there were about 169 newspapers published
in vernacular languages and their circulation reached
about 100,000. The Indian press has played a notable
role in mobilizing public opinion, organi-sing political
movements, fighting out public controversy and
promoting nationalism. Government policies were
constantly criticized in the pages of the newspapers,
Indian opinion was popularized and the idea of selfgovernance, democracy and Indian industrialization
was propagated among the masses through these
vernacular papers. Indian press was also an important
medium of constant exchange of ideas and opinion
among the nationalist in different parts of the country.
Newspapers, journals, pamphlets, magazines,
booklets and other printed materials were used to
propagate nationalism. Bamkim-Chandra Chatterjee
(Bengal), Rabinder Nath Tagore (Bengal), Laxminath
Bej Barua (Assam), Vishnu Sashtri Chiplankur
(Maharashtra), Subramanian Bharti (Tamil Nadu),
Altaf Hussain Hali (Urdu) and Bhartendu Harishchandra & Premchand (Hindi) were some of the
nationalist writers of the age. Newspapers like the
Indian Mirror, the Bengalee, the Armit Bazzar Partrika,
Bombay Chronicle, the Hindu Patriot, the Mahratta,
Kesari, Andra Prakashika, the Hindu, Induprakash,
Kohinur, Times of India, etc. in English and different
Indian languages exposed the excesses of British Indian
administration apart from popularizing among the
people the ideas of representative government, liberty,
democratic institutions, Home rule and Independence.
It may not be an exaggeration to state that the press
became the mirror of India's nationalism and the
primary medium of popular public education.</li>
        <li><b>Racialism:</b> One unfortunate legacy of the rebellion
of 1857 was the feeling of racial bitterness between
the rulers and the ruled. The 'punch' cartooned
Indians as half-gorilla, half-Negroes. The AngloIndian bureaucracy developed an attitude of
arrogance and contempt towards the Indians. They
somehow came to the conclusion that the only
argument that worked effectively with the Indians
was superior force. Thus, Europeans developed
their own social code of ethics and worked out the
theory of a superior race. The Indians were dubbed
as belonging to an inferior race and no longer
worthy of any trust the Indians were frequently
referred to as a nation of liars, perjurers and
forgers. The Anglo-Indians lobby produced books
leaf lets and pamphlets to justify the racial
superiority of the European races particularly the
English. This narrow approach evoked a reaction
in the Indians mind and put the educated-Indians
on the defensive.</li>
        <li><b>Impact of Contemporary European Movement:</b>
Contemporary story currents of nationalist ideas,
which pervaded the whole of Europe and South
America, did stimulate Indian Nationalism. A
number of nation-states came into existence in
South America on the ruins of the Spanish and
Portuguese empires. In Europe, the national
liberation movements of Greece and Italy in general
and of Ireland in particular deeply stirred the
emotions of Indians. Educated Indians touring
Europe were greatly impressed by the nationalist
movements. We find Surendranath Banerji
delivering lectures on Joseph Mazzini and the
"Young Italy'' movement organised by him. Lala
Lajpat Rai very often referred to the campaigns of
Garibaldi and the activities of coronaries in his
speeches and writings. Thus, European nationalist
movements denied strength to the developing
nationalism in India.</li>
        <li><b>Progressive Character of socio-Religious Reforms:</b>
In the 19th century educated Indians began to
examine afresh their religious beliefs and customs
and their social practices in the light of new
knowledge of western science and philosophy
which they had overturned. The result was various
religious and social reform movements in Hindu
religion like the Brahmo Samaj, the Prarthana
Samaj, the Arya Samaj, the Ramkrishna Mission,
the Theosophical society, etc. Similarly movements
reformed Muslim, Sikh and Parsi societies also.
In the religious sphere the reform movements
combated religious superstitions, attacked idolatry,
polytheism and hereditary priest hood. In the social
sphere, these movements attacked the caste system,
untouchability and other social and legal
inequalities. These movements were progressive
in character for they sought reorganization of
society on democratic lines and on the basis of
ideas of individual equality, social equality, reason,
enlightenment and liberalism. Most of the religious
societies had also political mission, all the source,
whosoever, came under their influence rapidly
developed a sense of self-respect and spirit of
patriotism.</li>
        <li><b>Lord Lytton's Reactionary Policies:</b> The
shortsighted acts and policies of Lord Lytton acted
like catalytic agents and accelerated the movement
against foreign rule. The maximum age limit for
the I. C. S. examination was reduced from 21 years
to 19 years, this making it impossible for Indians
to compete for it. The grand Delhi Durbar of 1877,
when the country was in the severe grip of famine,
solicited the remark of a Calcutta journalist that
'Nero was fiddling while Rome was burning'.
Lytton put on the statute book two obnoxious
measures the vernacular Press Act and Indian
Arms Act (1878). Lytton's unpopular acts provoked
a great storm of opposition in the country and led
to the organisation of various political associations
for carrying on anti-government propaganda in
the country.</li>
        <li><b>The Ilbert Bill Controversy:</b> The Ilbert Bill
controversy raised passion on both sides which
did not subside early. Ripon's movement sought
to abolish 'Judicial disqualification based as race
distinction' and the Ilbert Bill sought to give the
Indian members of the covenanted civil services
the same powers and rights as the European
colleagues enjoyed. The Bill raised a storm of
agitation among the members of the European
community and they all stood united against the
Bill. Ripon had to modify the Bill that almost
defeated the original purpose. The Ilbert Bill
controversy proved an eye opener to the Indian
intelligentsia. It became clear to them that justice
and fairplay could not be expected where the
interests of the European community were
involved. Further, it demonstrated to them the value
of organised agitation.
<br>
<br>
After 1870's, it became clear that the Indian
Nationalism had grown and had earned such
strength and courage to become an important part
in the Indian politics. Now, it was impossible to
ignore the Indian Nationalism. In 1885, the Indian
Nationalism was expressed in the form of an allIndian organisation called the India National
Congress. Before the National Congress, also there
was several political organizations in India though
on a lesser scale and limited to certain regions.</li>
    </ul>
</ol>


<div class="subheading"><strong><i>Pre-Congress Political Associations</i></strong></div>

The Indian sub-continent witnessed the growth of
political ideas and political organizations hitherto
unknown to the Indian world. And it was political
association which heralded 19th century India into
modern politics. After 1836, there was rise of many
political associations in various parts of India. All
these associations were headed by 'elites' and were
regional and local. What distinguished these new
political associations from earlier religions and caste
associations of the country were the secular interest
that bonded together the new classes. They worked for
administrative reforms and demanded participation
of Indians in the administration of India. Their method
was, however, polite and restricted to petitions to the
Government demanding reforms.

<div class="subheading"><strong><i>BENGAL PRESIDENCY</i></strong></div>

Raja Ram Mohan Roy was the pioneer of political
movement in India. He was greatly influenced by
western ideas. In 1821, the Raja celebrated in Calcutta
the establishment of a constitutional government in
Spain. Ram Mohan Roy was the first Indian to focus
the attention of the English men on the grievances of
India and to ask for remedial measures. He demanded
liberty of the press, appointment of Indians in civil
courts and other higher posts, codification of law, etc.
It was generally believed that some of the beneficent
provisions in the Charter Act of 1833 were due to his
lobbying in England.
<br>
<br>
The task of organizing political association, was,
however, left to the associates of Ram Mohan Roy. The
first such association called 'Bangabhasa Prakasika
Sabha'' was formed in 1836. The association discussed
topics connected with the policy and administration
of the Government and sought redress by sending
petition and memorials to the Governments. In July
1838, the "Zamindari Association'', more popularly
known as the "Landholders Society'', was formed to
safeguard the interests of the landlords. Although
limited in its objectives, the landholders Society marked
the beginning of an organised political activities and
use of methods of constitutional agitation for the
redressal of grievances.
<br>
<br>
In April 1843, another political association under
the name of the Bengal British India Society was
founded with the object of "the collection and
dissemination of information relating to the actual
condition of the people of British Indian'' on October
29, 1851, the two associations (Land Holders Society
and British India Society) were merged into a new one
referred the ``British India Association''. This
association was dominated by members of the landed
aristocracy and its primary objective was safeguarding
their class interest. However, the Association struck a
liberal note and when the time came for the renewal
of the charter of the East India Company it sent a
petition to the Parliament praying for establishment of
a separate legislature of a popular character, separation
of judicial and executive functions, reduction in the
salaries of higher officers, abolition of salt duty, able
abkari and stamp duties etc. The prayers of the
Association were partially met and the Charter Act of
1853 provided for the addition of six members to the
governor-general's council for legislative purpose.
In September 1875, Babu Sisir Kumar Ghose
founded the Indian league with the objective of
"stimulating the sense of nationalism amongst the
people" and of encouraging political education. Within
a year of its foundation, the Indian league was
superseded by the Indian Association, founded on 26
July 1876, by Anandamohan Bose and Surendranath
Banerjee. It was one of the most important preCongress Associations of political nature. It was
founded in Calcutta. The young nationalists of Bengal
were disheartened from the zamindar centric and
traditional nature of the British India Association. They
were in favour of a strong political struggle including
important social issues. They got a good educated
leader and orator in the form of Surendranath Banerjee.
Surendranath was dismissed by his higher officials
from the Indian civil services in a very unrightful
manner. He was against the supremacy of English
authorities and Englishmen in Indian civil services
and had raised voice against them. Surendranath
started his political career by talking on various
political issues in 1875 amongst the students of
Calcutta. The Indian Association hoped to attract not
only the middle classes but also the masses and
therefore kept its annual subscription of Rs 5 as
opposed to the subscription of Rs 50. p. a fixed by the
British Indian Association. Soon the Indian
Association became the centre of the leading
representatives of the educated community of Bengal.
The regulation of 1876 that reduced the maximum
age for appearing in the Indian Civil Service
examination from 21 to 19 years triggered on the
political activity in India. The Indian Association took
up this question and organized an all-India agitation
against it, popularly known as the Indian civil service
agitation. Surendranath Banerjee on a whirlwind tour
of northern India in May 1877 visited Banaras,
Allahabad, Kanpur, Lucknow, Aligarh, Delhi, Meerut,
Amritsar and Lahore. At certain centers he visited,
new political organizations to act in concert with the
Indian Association of Calcutta were set up.


<div class="subheading"><strong><i>BOMBAY PRESIDENCY</i></strong></div>

On the lines of British India Association of Calcutta,
on 26 August 1852, was founded the Bombay
Association with the object of 'memorializing from
time to time the government authorities in India or in
England for the removal of existing evils, and for the
prevention of proposed measures which may be deemed
injurious or for the introduction of enactment which
may tend to promote the general interest of all
connected with this country'.
<br>
<br>
The Bombay Association sent a petition to the
British Parliament urging the formation of new
legislative council to which Indians should also
represented. It also condemned the policy of exclusion
of Indians from all higher services, lavish expenditure
on sinecure posts given to European. However, this
Association didn't survive for long. The reactionary
policies of Lytton and the Ilbert Bill controversy caused
political commotion in Bombay. The credit for
organisation of the Bombay Presidency Association in
1885 goes to the popularly called brothers in lawMehtas, Telang and Tyabji, representing the three chief
communities of Bombay town. At Poona, the Poona
Sarvajanik Sabha was established in 1867 with the
object of serving as a bridge between the Governments
on the one hand and the people on the other.

<div class="subheading"><strong><i>MADRAS PRESIDENCY</i></strong></div>

A branch of the British Indian Association of
Calcutta was setup at Madras under the name of the
Madras Native Association. However, the Madras
Native Association right from its inception was worked
by some officials, possessed very little vitality, had
hardly any hold upon the public mind and languished
into obscurity after 1857.
The Madras Mahajan Sabha was formed in May,
1884 to co-ordinate the activities of local association
and to 'provide a focus for the non-official intelligence
spread up through the Presidency'. It was founded by
M. V. Raghavachari, G. Subrahmanyam Aiyar, Anand
Charlu and others.
<br>
<br>
Various political organizations were also formed
outside India during pre-Congress period of colonial
rule. In 1866, East India Association was founded by
Dadabhai Naoroji in London. It objective was to discuss
the problem and questions related to India and to
influence the British leaders towards the development
of India. Later, Dadabhai also opened its branch in
various important Indian cities. Two other Associations
namely National Indian Association, founded by Mary
Carpenter in 1867 and Indian society, founded by
Anandmohan Bose in 1872 were also formed in
London. These, however, were not so important as
compared to East India Association. Its leaders, like
Dadabhai Naoroji devoted all his life for Indian
freedom struggle. He was also known as the Grand
Old Man of India. He was the first economic thinker
of India. He, in his writings proved that the only cause
of poverty in India was the economic exploitation of
India by British and Drain of Wealth. Dadabhai
Naoroji was elected to the presidentship of Indian
National Congress thrice.
<br>
<br>
The political Associations and activities in preCongress period in India and abroad regarding the
Indian freedom struggle made it mandatory to form an
All-India Association that would lead the country
against the foreign rulers. These early Associations
had, though, important contribution i.e. of arousing
the political will and demands of the Indian public,
but their area and activities, all were limited. They
mainly questioned local issues and their members and
leaders were also limited to one or adjoining provinces.
Despite good leaders like Surendranath Banerjee,
Dadabhai Naoroji, Ananda Charlu and others there
was a lack of national unity in case of political
association that was gained by the formation of Indian
National Congress.



</div>