<div class="mtop25">

<h3>Europe</h3>

<div class="subheading"><strong><i>Introduction</i></strong></div>

Europe is the world's second smallest continents occupying the western tip of Eurasian
landmass. The old high lands lies to the north
and west with the high peaks of Alps in the
south. Europe's northern coastline stretches
deep into the Arctic Circle. Here the Norway
iceberg drift into the deep wide bottomed fjords.
The north European plain has low rolling-hills
and plains. Much of the area is cultivated and
used for growing crops like wheat and sugar
beet. Some of the world's oldest rocks are found
in northwest Europe. Erosion by glaciers in the
last ice age created smoothed hills such as the
mountain of Wales. The Alps are Europe's
major mountain chain. They were formed about
65 million years ago.

<div class="subheading"><strong><i>Climate</i></strong></div>

Europe's climate is temperate with few climatic extremes. In the far north, Europe extends into the Arctic Circle and the climate is
so cold that in the winter, the Baltic Sea freezes
over. Towards the Atlantic coast in the west,
the climate becomes wetter and warmer because of a warm ocean current known as the
'Gulf Stream'. The countries such as Italy and
Spain, which borders the Mediterranean Sea,
have long hot summers and low rainfalls.

<div class="subheading"><strong><i>Industry</i></strong></div>

The Western Europe has some of the
world's wealthiest countries. In countries such
as France, Germany and U.K. traditional industries like iron and steel making are now
being replaced by light industries such as electronics and services like finance and insurance.
In Eastern Europe, industry was subsidized by
the communist government for years. Many factories are old fashioned and need investment
to improve their equipment and production
methods.

<div class="subheading"><strong><i>Minerals</i></strong></div>

Europe has a few sizeable reserves of metallic minerals; most were used by industry
during the last century. Oil, gas and coal are
found in large quantities-gas in Northern Sea
and oil in Volga basin.


<div class="subheading"><strong><i>Land Use and Agriculture</i></strong></div>

The North European plain is the heart of
agriculture in Europe where fertile soil and
ample rainfall mean that a variety of crops can
be grown. Wheat is the main grain crops and
a wide range of fruit and vegetable are also
grown. Dairy and beef cattle are raised for their
milk and meat throughout Europe. In the south,
the Mediterranean climate allows citrus fruit
and olives to grow. Forest covers much of the
northern Scandinavia, while in the hills of British Isles sheep forming is common.

<div class="subheading"><strong><i>Northern Europe</i></strong></div>


<div class="subheading"><strong><i>Landscape</i></strong></div>

The Northern Europe consists of the countries like Denmark, Estonia, Finland, Iceland,
Latvia, Lithuania, Norway and Sweden. Denmark, Sweden and Norway are together known
as Scandinavia. Estonia, Latvia and Lithuania
are known as "Baltic States". The Scandinavia
is extremely rugged and mountainous with
landscape eroded by ice.
<br>
<br>
In the South of Scandinavia, the land is flatter,
with fertile soil deposited by glaciers. Much of
Finland, Norway and Sweden is covered by
dense forest. The Baltic States are much lower
with rounded hills and many lakes and
marshes. Iceland is one of world's most active
volcanic areas. There are about 200 volcanoes
on the islands, along with bubbling hot springs,
mud-holes and geysers which spurt boiling
water and steam high into the air. Norway has
many Fjords, deep, wide valley drowned by
seawater when the ice melted at the end of the
last Ice Age. Ships from Finland, Sweden and
Baltic states use the Baltic Sea as their route to
the North Atlantic Ocean. In winter, much of
the sea is frozen. The Finland and Sweden have
many thousands of lakes. During the last IceAge, glacier scoured hollows which filled with
water when the ice melted. The wide Courland
Spit runs for 100 km. along the Baltic coast at
Lithuania and the Russian enclave of
Kaliningrad. It encloses a huge lagoon.

<div class="subheading"><strong><i>Climate</i></strong></div>

The warm ocean currents flowing north
along the coast of Norway and Iceland make
the climate mild and wet. Away from the sea,
the climate is generally colder and drier.

<div class="subheading"><strong><i>Industry</i></strong></div>

In Scandinavia, many natural resources are
used in industry; timber for paper and furniture, iron for steel and cars. Fish and natural
gas are sourced from the seas. Hydro-electric
power is generated by waters flowing down steep
mountain slopes. The Baltic States still rely on
Russia to supply their raw material and energy.

<div class="subheading"><strong><i>Population</i></strong></div>

The population is distributed mainly along
the warmer and flatter southern and coastal
areas. The total population and its densities are
low for all the countries, and Iceland has the
lowest population density in the Europe, with
just three people per 59 sq (square) km. Many
Scandinavian have holiday homes in the islands, along the lake shores.

<div class="subheading"><strong><i>Farming and Land-Use</i></strong></div>

The southern Denmark and Sweden are
most productive areas, with pig farming, dairy
farming and crops such as wheat, barley and
potatoes. Sheep farming is important in Southern Norway and Iceland. In the Baltic States
cereal, potatoes and sugar beet are main crops
and cattle graze on dump pasture.

<div class="subheading"><strong><i>The Low Countries</i></strong></div>


<div class="subheading"><strong><i>Landscape</i></strong></div>

It consists of Belgium, Luxembourg and
Netherlands. These are called Low Countries
because most of their land is flat and low-lying. Much of the Netherland lies below sea
level. The low countries of Europe are most
densely populated countries, but most of their
people have a high living standard. The Low
Countries are largely flat and low lying. The
two major rivers- the Meuse and the Rhine flow
across the low countries of their mouth in the
North Sea. At the coast of river Rhine deposit
large quantities of sediments to form delta. In
the Netherland land has been reclaimed from
the sea since the Middle age by building dykes
and drainage ditches. These areas of land are
called 'Polders'. They are very fertile. The River
Rhine erodes and carries large amount of sediments along its course. When it reaches the
Netherlands it divides into three rivers. As they
approach the North Sea, the rivers slow down
depositing the sediments to form delta. The
plain of Flanders in western Belgium has fertile soil which was deposited by glaciers during the last Ice Age. They provide excellent land
for growing crops. The heartlands on the
Dutch-Belgium border have thin sandy soils.
The only plants which grow here are heathers
and gorse. The hill of Ardennes was formed
over 300 million years ago. They have many
deep valleys, which have been eroded by rivers
like Meuse.

<div class="subheading"><strong><i>Climate</i></strong></div>

The Low Countries share a similar climate
with mild winters and warm summers. Only
in the upland Ardennes region does rainfall
increase and temperature decrease.

<div class="subheading"><strong><i>Industry</i></strong></div>

The low-countries are an important centre for the hi-tech and electronic industries.
Good transport links to the rest of the Europe
allow them to sell their product in other countries. The built up area stretching from
Amsterdam in the Netherlands to Antwerp in
the Belgium has the greatest number of factories. Luxembourg is also an 
important banking centres, many international banks have its
head quarter in its capital city.

<div class="subheading"><strong><i>Population</i></strong></div>

More than 25 million people live in Low
Countries and nine out of every ten people live
in town or city. The largest urban area-known
as the 'Randstad Holland' is in the Netherlands.
It runs in an unbroken line from Rotterdam in
the south to Amsterdam in the west. Even most
rural areas in the Low Countries are densely
populated.

<div class="subheading"><strong><i>Farming and Land-Use</i></strong></div>

The fertile soil and flat plain of Low Countries provides excellent condition for farming.
The main crops grown are barely potatoes, and
flax for making linen. In the Netherlands much
farmland is used for dairy-farming. The country is also famous for growing flowers.

<div class="subheading"><strong><i>The British Isles</i></strong></div>


<div class="subheading"><strong><i>Landscape</i></strong></div>

The British Isles consists of the countries of
United Kingdom and Republic of Ireland. It
lies off the Northwest coast of mainland Europe. They are made up of two large islands
and 500 smaller ones. Politically, the region is
divided into two countries: the United Kingdom-England, Wales, Scotland and Northern
Islands and the Republic of Ireland. Geographically, the British Isles are divided between highlands to the north and west, and lowlands to
the south and east.
<br>
<br>
The Ben Nevis Mountain is the highest
point in the British Isles. It is 1,343 m above the
sea level. The Lake District National Park has
England's highest peak. Scafell Pike, at 978 m
is deepest lake. Wastwater (80 m) is its largest
lake. The Pennines are a chain of high hills
topped by Moorland. They run for over 400
km and are known as the 'backbone of England'. The Fens is the flattest area in England.
Much of the land here has been reclaimed from
the sea. Rias are rivers valley that have been
drowned by rising sea level. The southern coast
of southwest England has many good examples. The Burren is a large area of limestone
rock in the west of Ireland. Its flat surfaces are
known as limestone pavements.

<div class="subheading"><strong><i>Climate</i></strong></div>

'The British Isles' climate is moderated by
the warm Atlantic ocean current called 'GulfStream'. The west is generally wetter than the
east and the south warmer than the north.

<div class="subheading"><strong><i>Industry</i></strong></div>

The United Kingdom's traditional industries
such are coal-mining, iron and steel-making and
textiles have declined in recent years. Today,
newer industries make cars, chemicals, electronic and high-tech goods. Service industries
especially banking and insurance have grown
in importance. The country's most valuable
natural resources are its large North Sea oil
and fields.

<div class="subheading"><strong><i>Population</i></strong></div>

The United Kingdom is densely populated
with most of the people living in urban areas.
The Southeast is the most crowded part of the
country. The Scottish highlands are populated
today than they were 200 years ago. Ireland is
still mainly rural, with many Irish people making their living from farming.

<div class="subheading"><strong><i>France</i></strong></div>


<div class="subheading"><strong><i>Landscape</i></strong></div>

Andorra, France and Monaco are the chief
countries in these zones. The north and west
of France is made up of mainly flat, grassy
plains and low hills. Wooded mountain line
the country border in the south and east and
much of central France is taken up by Massif
Central, an enormous plateau, cut by deep 
rivers valley and scattered with extinct volcanoes.
Three major rivers. The Loire, Seine and
Garonne drain the low land basins. The Paris
Basin is a saucer-shaped hollow made up of
layers at hard and soft rock covered with very
fertile soil. It runs across about 100,000 sq.
km. of Northern France. The Western end of
the European Alpine Mountain chain stretches
into southeast France. The French Alps can be
crossed by several passes, which give access to
Italy and Switzerland.
<br>
<br>
The coast of Normandy is lined with high
chalk cliff. The Mount Blanc in the French Alps
is the tallest in Eastern Europe. It is 4,807 m.
high. Pyrenees Mountain forms a natural barrier between France and Spain. Several of their
peaks reach heights of over 3,000 meter. The
Pyrenees are difficult to cross, due to their
height and because they have few low passes.
The vast granite plateau of Massif Central was
formed over 200 million years ago. Volcanic
activity here only stopped within the last 10,000
years and regions rounded hills are the worn
down remains of the volcanic mountain. The
Camargue is an area of marshes, pastures, sand
dunes and salt flats at the mouth of the river
Rhone. Rare animal and plant are found there.

<div class="subheading"><strong><i>Climate</i></strong></div>

In winter, the coldest areas of France are
mountain of the Massif Central and the Alps.
Summer is the hottest on Mediterranean coast.

<div class="subheading"><strong><i>Industry</i></strong></div>

France is one of world's top manufacturing nations, with a variety of both traditional
and high tech industries. Cars, machinery and
electronic products are exported worldwide,
along the luxury goods such as perfumes, fashion and fine wines. Fossil fuel provides some
energy, but France is currently the world's second biggest producer of Nuclear power.

<div class="subheading"><strong><i>Population</i></strong></div>

In the past 50 years, most people have moved
from the countryside into the urban areas. Paris
and its suburb, the industrial cities, and the Cote
d'Azur in the southeast are parts of France and
now have the biggest population.

<div class="subheading"><strong><i>Farming and Land-Use</i></strong></div>

France is able to produce a variety of crops
because of its rich soil and mild climate. Wheat
is grown in many parts of north, along with
potatoes and other vegetables. Fields of maize
and sunflower and fruit orchards are found in
the south, while grapes for the famous wine
industry grown across the country. Beef and
dairy cattle are grazed on low-lying pasture.

<div class="subheading"><strong><i>Spain And Portugal</i></strong></div>

<div class="subheading"><strong><i>Landscape</i></strong></div>

Spain and Portugal occupy the Iberian
Peninsula which is cut off from the rest of the
Europe by the Pyrenees. Over the centuries,
Iberia has been invaded and settled by many
different peoples. The most of the inland in
Spain is taken up by Meseta, a dry almost treeless plateau surrounded by steep mountain
ranges. The only lowlands apart from narrow
stripes along the Mediterranean coast are the
valleys of the Ebro, Tagus, Guadiana and
Guadalquivir rivers. Portugal coast is lined by
wide plains. Inland, the river Tagus divides the
country in two. To the north, the land is hilly
and wooded; to the south it is low-lying and
drier. The river Ebro carries vital irrigation
water to Spain's northeastern plains before flowing into the Mediterranean Sea. The westward
flowing rivers- Duero, Tagus, and
Guadalquivir- flow across the Meseta on their
courses to the Atlantic Ocean. The Southern
end of Mesta is marked by Sierra Morena
mountain range. Mulhacen is the snow capped
Sierra Nevada range in southern Spain is 3,481
m high. It is Iberia's tallest mountain.

<div class="subheading"><strong><i>Climate</i></strong></div>

The Northern Spain is wetter and cooler
than the South. On the central plateau, summers are very hot and dry, and 
winter oftenfreezing. The North of Portugal is cooled by
winds blowing off Atlantic Ocean. The south
is warmer with dry mild winter.

<div class="subheading"><strong><i>Industry</i></strong></div>

Madrid Barcelona and the northern parts
are Spain's chief industrial centres. Here, Iron
ore from Spanish mines is used to make steel,
and factories produce cars, machinery and
chemicals. Portugal exports textiles clothing and
footwear, along with fish such as sardines and
tuna caught off the Atlantic coast. In both
countries tourism is very important to the
economy.

<div class="subheading"><strong><i>Industry</i></strong></div>
Population
In the first half of the 20th century most
Spaniards lived in villages or small towns, scattered around the countries. Today tourism and
industry have drawn most of the population to
the cities and coastal areas. Most Portuguese
still live in rural areas along the coast or in the
river valley, but the cities are growing fast.
Farming and Land Use
Cereals especially wheat and Barley are
Iberia's chief crops. In the dry south of Spain,
the land is irrigated to grow citrus fruits especially orange and vegetable. In both countries
olive trees and vineyard occupy large area of
land. Olive oil and wine are important export.
Cork oak trees from Iberia forest supply 80 per
cent of the world cork.

<div class="subheading"><strong><i>Germany And Alpine States</i></strong></div>


<div class="subheading"><strong><i>Landscape</i></strong></div>

It consists of Austria, Germany,
Liechtenstein, Slovenia and Switzerland. Germany is the biggest power in the continent. To
the north, flat plains and heathlands surround
the North Sea coast. Further south are
Germany's central uplands which are lower
and older than the jagged peaks of the Alps,
which began to form about 65 million years
ago. From its source in the Black forest, the
River Danube flows eastward across Germany
and Austria on its course to the Black Sea. The
other major river, the Rhine, flows northward.
The Rhine is Germany's main waterway. It is
an important transport route to and from
Northern ports. It twists and turns across 1,320
km of Europe from its source in southeast
Switzerland to the North Sea. The Danube is
Europe's second longest river flowing 2,840 km.
Lake Constance covers 54 sq km and is
Germany's largest lake, although its water are
shared by Austria and Switzerland. The Alps
were formed when African plate collided with
the Eurasian plate, pushing up and crushing
huge amount of rock, to form mountain. The
Harz Mountains are much older than the Alps.
They were formed over 300 million years ago.
Most of the water of the limestone Karst region
of Slovenia flows underground through huge
caves and caverns.

<div class="subheading"><strong><i>Climate</i></strong></div>

Winter temperature decreases eastwards
and the high alpine region is coldest. Climate
variations in the Alps are common due to turbulent airflows.

<div class="subheading"><strong><i>Industry</i></strong></div>

Germany is a leading manufacturer of cars,
chemicals, machinery and transport equipment.
Switzerland and Liechtenstein with few raw
materials make high value products such as
watches and pharmaceuticals and provide services such as banking. The Alpine states are
popular tourist locations all year round.

<div class="subheading"><strong><i>Population</i></strong></div>

Western and central Germany are the most
densely populated areas in the region- particularly in and around the Rhine and Ruhr valleys, where there are many industries. In the
south, the steep slopes of the Alps and permanent snow cover on the higher peaks means
that most large towns and cities are in scattered lowland area.

<div class="subheading"><strong><i>Farming and Land Use</i></strong></div>

Germany produces three quarters of its
own food. Crop farming is widespread, with
cereals and root grown in flat fertile areas.
Cattle and Pig rearing supply meat and dairy
products. Across the Alps, the mountains limit
farming, although vines are grown on the
warmer south facing slopes. The rich pastures
of the lower slopes are used to graze beef and
dairy cattle.

<div class="subheading"><strong><i>Italy</i></strong></div>

<div class="subheading"><strong><i>Landscape</i></strong></div>

Italy is a type of peninsula jutting south
from mainland Europe into Mediterranean Sea.
In Northern and Central Italy the land is mainly
mountainous. Most of the flat land is in Po
Valley and along the eastern coast. Italy lies
within an earthquake zone which makes the
land unstable and there are also a number of
active volcanoes. The basins of the river Po has
the best soils in Italy. Rich alluvium is washed
from the mountains by the rivers to form a
wide plain. The great lakes like Garda and
Como fill several south-facing valleys once occupied by glaciers. The Dolomites are high
mountains are parts of same range as the Alps.
<br>
<br>
They were formed 65 million years ago. The
Apennines mountain, range formed the backbone of the Italy dividing the rock west coast
from the flatter sandy east coast.
Sardinia Island is made from very old rocks
which were up-thrusted to form mountains.
The Tyrrhenian Sea divides the Italian mainland from Sardinia is gradually filling with
sediments from the rivers, which flows into it.
Sicily is the largest islands in Mediterranean. It
has a famous active volcano called 'Mount Etna'
and often experiences earth quakes.

<div class="subheading"><strong><i>Climate</i></strong></div>

The Alpine North has cold winters often
with snow. Further south temperature are
higher. Sicily has Italy's highest temperature
due to warm African wind.
Industry
Italian Industry is located mainly in the
north. Design is extremely important to Italians and they are proud of the elegant design
of their furniture, clothes and shoe. Though
many firms are small, they are very efficient.
Italy has few minerals resources so it needs to
import new materials to make cars, engine and
other high-tech products.

<div class="subheading"><strong><i>Population</i></strong></div>

Most of the Italy's population lives in the
North, mainly in and around the Po Valley,
which is home to over 25 million people. Most
people here have high standard of living. Southern Italy is much more rural towns are smaller
and life is often much harder.

<div class="subheading"><strong><i>Central Europe</i></strong></div>

<div class="subheading"><strong><i>Landscape</i></strong></div>

It consists of Czech Republic, Hungry,
Poland and Slovakia. The high Carpathian
Mountains sweep across the northern Slovakia.
The lower Sudeten Mountain lies on the border of the Czech Republic and Poland. Together
these mountains form a barrier which divides
the Great Hungarian plain and the Dannbe river
basin in the South from Poland and the vast
rolling lowlands of the North European plain.
Pomeriania is a sandy coastal area with lakes
formed by glaciers. It stretches west from the
River Vistula to just beyond the German border; Poland's largest river is the river Vistula. It
flows northwards passing through the capital,
Warsaw on the way to the Baltic Sea. The
Sudeten Mountains are famous for their hot
minerals springs. These occur where water
heated deep within the Earth's crust finds its
way to the surface along fracture in the rock.
The River Danube forms the border between
Slovakia and Hungary for over 162 km. It then
turns south to flow across the Great Hungarian plains. The Great Hungarian Plains covers
almost half of Hungary's land area. It is a
mixture of farmland and Steppe. The Tatra
Mountains are a small range at northern end
of the Carpathian Mountains. They include
Geriachousky which is central Europe's highest point at 2,655 m.

<div class="subheading"><strong><i>Climate</i></strong></div>

The Carpathian Mountains are both the
coldest and the wettest part of Central Europe.
Temperature plunges below zero across the
whole region during winter. In summer, eastern Hungary is the hottest place.

<div class="subheading"><strong><i>Industry</i></strong></div>

Brown coal or lignite is central Europe's
main fuel and one of Poland's major exports.
A variety of minerals are mined in the mountains of Czech Republic and Slovakia. Hungary has a wide range of industries producing
vehicles, metals and chemicals as well as textile and electrical goods. The Czech Republic is
famous for its breweries and glass making.

<div class="subheading"><strong><i>Farming and Land Use</i></strong></div>

Central Europe's main crops are cereals
such as maize, wheat and rye, along with sugar
beet and potatoes. In Hungary, sweet pepper
grows, helped by the warm summers and mild
winters. They are used to make paprika. Grapes
are also grown, to make wine. Large areas of
the plains of Hungary and Poland are used for
rearing pigs and cattle. Trees for timber grow
in the mountain of Slovakia and Czech Republic.

<div class="subheading"><strong><i>Population</i></strong></div>

Most people in central Europe live in low
laying areas, for example, along the River
Vistula in Poland and in the lowlands of the
Czech Republic. In mountainous Slovakia many
people still live in rural towns and villages. The
industrial areas and capital cities have the highest population densities.

<div class="subheading"><strong><i>South East Europe</i></strong></div>

<div class="subheading"><strong><i>Landscape</i></strong></div>

It consists of Albania, Bosnia and
Herzegovina, Bulgaria, Croatia, Greece,
Macedonia, Yugoslavia (Serbia and
Montenegro). The Southeast Europe is largely
mountainous with range running from northwest 
to southeast. The Dinaric Alps runs parallel to the Dalmatian coast, and the Pindus
Mountain continue this line into Greece. In the
Aegean Sea the drowned peaks of an old
mountain chain form thousands of islands. The
Vojvodina region of Yugoslavia is the southern
part of the great Hungarian plains. The plain
is flat and fertile soil allows grain crops like
corn and wheat to be grown.
<br>
<br>
The Balkan Mountains forms a spur running east to west through Bulgaria and separate the two main rivers the Danube and the
Maritsa. Dalmatian coast has many long, narrow islands near the shore. These were formed
as the Atlantic Sea flooded the river valley
which ran parallel to the coast. The Peloponnese
is a mountainous peninsula linked to the Greek
mainland only by a narrow strip of land called
an isthmus. There are two groups of Greek
islands-the Ionian island of the west of mainland Greece, and the more numerous islands
to the east in Aegean Sea.

<div class="subheading"><strong><i>Climate</i></strong></div>

The Southern Europe's climate varies from
north to south. Continental climates are found
in the north; winters are cold and dry while
towards the south, winters are milder and
summers much hotter. Europe's wettest place
is found in the mountain in Bosnia and
Herzegovina.

<div class="subheading"><strong><i>Industry</i></strong></div>

The mainland Greece and the many islands
in the Aegean Sea are centre of a thriving tourist trade, while tourism on the Black Sea coast
continues to grow. The Dalmatian coast had a
small, but growing tourist industry until the
civil war in former Yugoslavia disrupted that
and other industries. Heavy industries like
chemicals, engineering and ship-building remain an important source of income in Bulgaria.

<div class="subheading"><strong><i>Population</i></strong></div>

Greece population is mostly urban; over 50
per cent live in the capital Athens and in
Salonica. In Bulgaria, most people live in cities.
About half of Albania's and Macedonia's people
are still rural. Since the civil war, the different
ethnic groups in Bosnia and Herzegovina, Yugoslavia and Croatia have lived from one another.

<div class="subheading"><strong><i>Eastern Europe</i></strong></div>

<div class="subheading"><strong><i>Landscape</i></strong></div>

It consists of Belorussia, Moldavia, Romania and Ukraine. The flat and rolling grassland, marshes and rivers, flood plains covers
almost all of Ukraine and Belorussia. The
Carpathian Mountains cross the southwestern
corner of Ukraine and continue a large arc
shaped chain of high peaks at the heart of
Romania. Along the southern part of this chain
the Carpathians are called the Transylvanian
Alps. The Pripet Marshes in Belorussia and
Ukraine form the longest area of marshland in
Europe. The Steppes are great wide grassland,
which are found across Eastern Europe and
central Asia. Over 70% of the Ukrainian landscape is Steppe. The Crimea Peninsula divides
the Sea of Azov from the Black Sea. The steep
mountain of Krymsk Hory runs along the southeastern coast of Crimea.

<div class="subheading"><strong><i>Climate</i></strong></div>

The climate is continental with warm dry
summers and very cold dry winters. Temperatures are higher along the fringe of the Black
Sea while the Carpathian Mountains are colder
and wetter all year round.

<div class="subheading"><strong><i>Industry</i></strong></div>

In Ukraine, most industry is based on the
country's minerals reserve. The Donbas region
has Europe's largest coalfield and is an important centre for iron and steel production.
Belorussia's main industries are chemicals; machine building and food processing. Romania's
manufacturing industries are growing with the
help of foreign investment.

<div class="subheading"><strong><i>Farming and Land Use</i></strong></div>

The Black soils found across much of
Ukraine are very fertile and the country is a
big producer of cereals sugar beet and sunflowers, which are grown for their oil. In
Moldavia and southern Romania the warm
summers are ideal for growing grapes for wine,
along with sunflowers and variety of vegetables.
Cattle and Pigs are farmed throughout Eastern
Europe.

<div class="subheading"><strong><i>Population</i></strong></div>

Most Romanians live in Bucharest, the capital or in other cities and towns. In Ukraine,
two third of the population lived in the cities
in the Donbas industrial area. Most of the
Belorussian people are city dwellers. Moldova
is the most rural country in Eastern Europe;
half its people live in the countryside and make
their living from farming.

<div class="subheading"><strong><i>The Mediterranean</i></strong></div>

<div class="subheading"><strong><i>Landscape</i></strong></div>

The Mediterranean Sea separates Europe
from Africa. It stretches more than 4,000 km
from east to west. The Mediterranean Sea
would be an enormous lake if it were not for
strait of Gibraltar, a narrow opening only 13
km wide which joins it to the Atlantic Ocean.
The Mediterranean lies over the boundary of
two continental plates. The Mediterranean
coasts are bordered by several thousand miles
of sandy beaches. The area of sea off the coast
of Tunisia and also the Adriatic Sea are shallower than the rest of the Mediterranean. The
rugged Atlas Mountain runs through the most
of Morocco and Algeria. They form a barrier
between the Mediterranean and the Sahara,
which lies south to them. Greek Islands has
thousands of islands, which lie, both in the
Mediterranean and in the smaller Aegean Sea.
Some of them are the remains of old volcanoes
which has left black sand on the beaches. Suez
Canal links the Mediterranean to the Gulf of
Suez and the Red Sea. Before it was built ship
had to sail around the whole of Africa to reach
Asia.

<div class="subheading"><strong><i>Tourism</i></strong></div>

The tourism industry in and around the
Mediterranean is one of the most highly developed 
in the world. More than half of the world's
income from tourism is generated here. Resorts
have grown up along the northwest coast of
Africa, and in Egypt, in southern Spain, France,
Italy, Greece and Turkey, tourism brings huge
economic benefit.

<div class="subheading"><strong><i>Industry</i></strong></div>

The Mediterranean has a large fishing industry, although most of the fishing is smallscale. Tuna and Sardines are caught throughout the region and mussels are found off the
coast of Italy. Fish canning and packing takes
place at most of the larger ports. Small oil and
gas reserves are extracted off the coast of North
Africa and near Greece, Spain and Italy.

<div class="subheading"><strong><i>Points to Remember</i></strong></div>

<ol>
    <ul>
        <li>Europe is the sixth largest continent with
an area of 10,360,000 sq km.</li>
        <li>The highest point in Europe is Mont Blanc
(4807 m) in the Alps and Mt Elbrus (5633
m) in the Caucasus.</li>
        <li>Belgium and Netherlands are the two small
low lands countries very thickly populated.</li>
        <li>Iceland, Norway, Sweden and Denmark are
collectively known as Scandinavia.</li>
        <li>The Seine and Rhine are the important
rivers that join the English Channel and
the North Sea.</li>
        <li>The Volga, which is the largest river of
Europe, joins a landlocked Sea named the
Caspian.</li>
        <li>Elbrus is the highest mountain peak in
Europe, which lies in the Caucasus.</li>
        <li>Lombardy in Italy and the lowlands of
Andalusia in Spain and the plains of
Hungry are the lowlands.</li>
        <li>More than 700 million people live in Europe
and its population is highly urbanized.</li>
        <li>Rotterdam, in the Netherlands is a part of
conurbation, a large built up are with
several towns and cities.</li>
        <li>Temperate type of climate is found in
Europe.</li>
        <li>North European plain is the Europe's
agricultural heart.</li>
        <li>The Alps were formed when after can plate
collided with the Eurasian Plate.</li>
        <li>Estonia, Latvia and Lithuania are together
called 'Baltic State'.</li>
        <li>Belgium, Luxemberg and Netherlands are
called 'Low countries'.</li>
        <li>The plain of Flanders in Western Germany
has fertile soil.</li>
        <li>The Burren is a large area of limestone rock
in the west of Ireland. Its flat surfaces are
known as limestones pavements.</li>
        <li>The coast of Normandy is lined with high
chalk cliffs.</li>
        <li>The Duero, Tagus and Guadalquivir rivers
flow across the Meseta on their courses to
Atlantic Ocean.</li>
        <li>Germany is a leading manufacturer of cars,
machinery and transport equipment.</li>
        <li>Sicily is the largest islands in
Mediterranean. It has a famous active
volcano called Mount Etna.</li>
        <li>The Po Valley is a broad flat plain in North
of Italy.</li>
        <li>Sicily has Italy's highest temperature, due
to warm African winds.</li>
        <li>The Poland's largest river is Vistula. It flows
northwards, passing through the capital
Warsaw on its way to the Baltic Sea.</li>
        <li>The Tatra Mountains are small range at the
northern end of the Carpathian Mountains.</li>
        <li>The Balkan Mountains forms a spur running
east to west through Bulgaria and separate
the two main rivers, the Danube and the
Maritsa.</li>
        <li>Carpathian Mountain Range is the largest
mountain range in Eastern Europe. They
are rich source of timber and minerals.</li>
        <li>Suez Canal links the Mediterranean to the
Gulf of Suez and the Red Sea. Before it
was built, ship had to sail around the whole
of Africa to reach Asia.</li>
        <li>The Atlas Mountains runs through most of
Morocco and Algeria. They form barrier
between the Mediterranean coast and the
Sahara, which lies south of them.</li>
        <li>The Carpathian Mountains are both the
coldest and the wettest parts of central
Europe.</li>
        <li>Tyrrhenian Sea divides the Italian mainland
from Sardinia is gradually filling with
sediments from the rivers, which flow into
it.</li>
        <li>Poland's largest river is the Vistula. It flows
northwards passing through the Capital
Warsaw.</li>
        <li>Central Europe's main crops are cereals
such as maize, wheat and rye, along with
sugar beet and potatoes.</li>
        <li>The worst nuclear incident in history
happened at Chernobyl's nuclear power
station in Northern Ukraine.</li>
    </ul>
</ol> 



</div>